import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router';
import LogoutButton from '../buttons/LogoutButton';
import { useAppSelector } from '../../store/store';
const Navbar = () => {
    //const isAuth = false
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const { isAuth, role } = useAppSelector((state) => state.auth);
    console.log("state isAuth:", isAuth);
    return (_jsxs("nav", { className: `bg-white shadow-sm sticky top-0 z-50 dark:bg-gray-800 `, children: [_jsx("div", { className: "max-w-screen mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsx("div", { className: "flex items-center", children: _jsx(Link, { to: "/", className: "text-xl font-bold text-gray-700 hover:text-blue-600 dark:text-white dark:hover:text-blue-400 transition-colors", children: "App" }) }), _jsx("div", { className: "hidden md:flex items-center gap-x-3", children: isAuth ?
                                (_jsxs(_Fragment, { children: [_jsxs("div", { className: 'mx-auto', children: [_jsx(Link, { to: `/`, "data-testid": "dashboard", className: "px-5 py-2 text-sm font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 rounded-lg transition-colors dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Dashboard" }), role === "admin" && _jsx(Link, { to: `/users`, "data-testid": "users-link", role: "users", className: "px-5 py-2 text-sm font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 rounded-lg transition-colors dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Users" }), role === "admin" && _jsx(Link, { to: `/logs`, "data-testid": "logs-link", className: "px-5 py-2 text-sm font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 rounded-lg transition-colors dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Activity Logs" }), _jsx(Link, { to: `/profile`, "data-testid": "profile", className: "px-5 py-2 text-sm font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 rounded-lg transition-colors dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Profile" })] }), _jsx(LogoutButton, { isMobile: false, title: "Logout" })] }))
                                :
                                    _jsxs(_Fragment, { children: [_jsx(Link, { to: `/login`, "data-testid": "login-link", className: "px-5 py-2 text-sm font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 rounded-lg transition-colors dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Login" }), _jsx(Link, { to: `/register`, "data-testid": "register-link", className: "px-5 py-2 text-sm font-medium bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors dark:bg-blue-700 dark:hover:bg-blue-600", children: "Register" })] }) }), _jsx("div", { className: "-mr-2 flex md:hidden", children: _jsxs("button", { onClick: () => setMobileMenuOpen(!mobileMenuOpen), type: "button", className: "inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white dark:text-gray-300 dark:hover:text-white dark:hover:bg-gray-700", "aria-controls": "mobile-menu", "aria-expanded": mobileMenuOpen ? "true" : "false", children: [_jsx("span", { className: "sr-only", children: "Open main menu" }), mobileMenuOpen ? (_jsx("svg", { className: "block h-6 w-6", xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" }) })) : (_jsx("svg", { className: "block h-6 w-6", xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M4 6h16M4 12h16M4 18h16" }) }))] }) })] }) }), mobileMenuOpen && (_jsx("div", { className: "md:hidden", id: "mobile-menu", children: _jsx("div", { className: "px-2 pt-2 pb-3 space-y-1 sm:px-3", children: isAuth ?
                        (_jsxs(_Fragment, { children: [_jsx(Link, { to: `/`, className: "block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Dashboard" }), role === "admin" && _jsx(Link, { to: `/users`, "data-testid": "users-link", className: "block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Users" }), role === "admin" && _jsx(Link, { to: `/logs`, className: "block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Activity Logs" }), _jsx(Link, { to: `/profile`, className: "block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Profile" }), _jsx(LogoutButton, { isMobile: true, title: "Logout" })] }))
                        :
                            _jsxs(_Fragment, { children: [_jsx(Link, { to: `/login`, className: "block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:text-blue-400 dark:hover:bg-gray-700", children: "Login" }), _jsx(Link, { to: `/register`, className: "block px-3 py-2 rounded-md text-base font-medium bg-blue-600 text-white hover:bg-blue-700 dark:bg-blue-700 dark:hover:bg-blue-600", children: "Register" })] }) }) }))] }));
};
export default Navbar;
